### ISSUE TITLE
Create design wireframes for the app

### ISSUE THREAD

**Issue by jddeep** [AOSSIE-Org/Resonate#1]
Use tools like Figma or Sketch to design the wireframes.

**Comment by adityakanu** [comment]
I already have the design for the web version ready. @jddeep can please assign this to me as I will start working on the mobile design as well.

**Comment by deekshatw** [comment]
Hey! If no one's working on this, can I work on this?

**Comment by chandansgowda** [comment]
Is anyone working on this issue already?

**Comment by Axhaat** [comment]
@chandansgowda 
Yes, I am working on the mobile design already.

**Comment by chandansgowda** [comment]
@Axhaat make sure to use the colour scheme used by AOSSIE's website.

**Comment by chandansgowda** [comment]
@Axhaat 
Any update ?

**Comment by kartiksureja** [comment]
> Is anyone working on this issue already?

Hey , would liek to take up the design .Have started working on it and will submit it to you before tonight.

**Comment by kartiksureja** [comment]
Hey , would like to take up the design work .Have started working on it and will submit the figma with wireframes to you before tonight.

**Comment by chandansgowda** [comment]
Hey @kartiksureja 
This is good. But can we give it more of a minimalistic look ?

**Comment by chandansgowda** [comment]
Hey @kartiksureja 
Since its getting too delayed, for now we are going with the following basic layout. Please feel free to suggest improvements or a whole new better User Interface. 

SignIn Screen            |  Signup Screen | User Onboarding           
:-------------------------:|:-------------------------:|:-------------------------:
![login](https://github.com/AOSSIE-Org/Resonate/assets/41890434/10610ef3-5475-4c46-85a2-8034530b1f70)  |  ![signup_screen](https://github.com/AOSSIE-Org/Resonate/assets/41890434/9409391c-1f3a-478f-bb79-b9b70de94037) | ![onboard](https://github.com/AOSSIE-Org/Resonate/assets/41890434/37063293-882b-42ae-b344-1373b19b6f2a)

Rooms Screen | Create Room Popup            |  Single Room Screen
:-------------------------:|:-------------------------:|:-------------------------:
![rooms_screen](https://user-images.githubusercontent.com/41890434/229134926-313fae1b-2f5d-4d19-b036-2082cf24f347.png) | ![create_room](https://user-images.githubusercontent.com/41890434/229134951-d7b6d77b-8a6d-4fc7-8fd9-99bba6b56bc3.png)  |  ![room_screen](https://user-images.githubusercontent.com/41890434/229136723-02c56d8d-137b-466b-9743-5027ab062fd6.png)

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda is this issue dealt with would it be alright to close it now just to attain a better state of the repository
