### ISSUE TITLE
Document the architecture

### ISSUE THREAD

**Issue by jddeep** [AOSSIE-Org/Resonate#2]
State how you are going to build something like a Clubhouse or Twitter spaces.
- How is audio streaming going to be handled
- How are people going to join in a space

A lot of questions. Research and come up with answers.

**Comment by KlausMikhaelson** [comment]
Hey @jddeep would like to work on it !

**Comment by Onyx2406** [comment]
Audio streaming: Audio streaming requires a scalable and robust solution that can handle large volumes of data without sacrificing quality. WebRTC is an open-source project that provides real-time communication between browsers and mobile applications, making it an ideal choice for handling audio streaming. Socket.IO is another popular choice for handling real-time communication between the server and the client. Can also use RTMP, is a protocol that provides low latency streaming over the internet and is used by platforms such as Twitch and Facebook Live.

Backend: To build the backend, Node.js is a perfect choice imo.

Frontend: Using JavaScript and ReactJS framework, we can build a good user interface.

User authentication and onboarding:

OAuth and OpenID Connect for user authentication. They allow users to sign up and log in to the platform using their Google, Facebook, or Twitter accounts. Once users are authenticated, they can create their profiles, set their interests, and follow other users.

Space creation and management:

we can use WebSockets, a protocol that provides real-time, bidirectional communication between the server and the client. This enables us to handle events such as user joining, leaving, and speaking in real-time.

Audio quality:

Audio quality is a crucial factor in social voice platforms. To ensure high-quality audio, we can implement noise reduction, echo cancellation, and other audio processing techniques. We can also use Adaptive Bitrate Streaming to adjust the audio quality based on the user's network conditions. ABS will ensure that users with poor network connections can still participate in the conversation without affecting the audio quality for others.

**Comment by Onyx2406** [comment]
Audio streaming: Flutter provides a package called audioplayers that can be used to play and control audio files. It supports various audio formats such as MP3, WAV, and FLAC. To handle real-time audio streaming, we can use a third party library such as Agora or Twilio.

Backend: To build the backend, we can use Node.js with Socket.IO, Ruby on Rails, or Django.

Frontend: Flutter provides a rich set of UI components that can be used to build the user interface. It also provides support for real-time updates using streams and reactive programming.

User authentication and onboarding:

For user authentication, we can use Firebase Authentication, to sign up and log in using their Google, Facebook, or Twitter accounts. Once users are authenticated, they can create their profiles, set their interests, and follow other users.

Space creation and management:

To implement space management, we can use a real-time database such as Firebase Realtime Database.

Audio quality:

To ensure high-quality audio, you can implement noise reduction, echo cancellation, and other audio processing techniques using third-party libraries. we can also use Adaptive Bitrate Streaming to adjust the audio quality based on the user's network conditions.

**Comment by chandansgowda** [comment]
Hey @Onyx2406 
Great job. Actually, I found some inconsistency and improvements in your plan. 
1. Since we are creating a backend ourselves, why are we using Firebase which is again a BaaS service?
2. I think we can build our own setup for handling realtime audio rather than using a paid third party service 
3. Since it's an open source project, we can consider adding SignIn with GitHub also.
4. Which architecture design pattern are we using ?
5. What will we use for state management?

**Comment by ViAsmit** [comment]
@D-Ajay-Kumar 

I loved your suggestion, and feeling very much aligned to your thoughts. 
But what do you say for MVVM(Model View View-Model) pattern for mobile application. I feel like it will be more suitable for application side. 
Any Comments?

Reference:
https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel
https://github.com/ViAsmit/Flutter_MVVM_With_GetIt

**Comment by ishivanshgoel** [comment]
@jddeep 

For audio streaming,
1. There are multiple options. Selecting one depends on the use case and the various related constraints. 
For sure there are multiple paid services available like Twilio, Dyte SDKs, etc but as we are building an open-source product we can utilize various open-source technologies like WebRTC.
2. WebRTC certainly has some scalability limitations (I faced them while working on a project), need to look more into it. 
3. Second option that comes to my mind right now is using the asterisk (IP PBX) for audio streaming. Asterisk is an open-source technology that powers VOIP calls (Voice over IP). 
4. In my opinion (based on a few experiments I did for comparison), VOIP calls are better than WebRTC calls in terms of voice quality and also scalability. 
By scalability (for audio streaming), I mean the number of users that can communicate at a time with each other.

For making people join a space,
1. It depends on the audio streaming platform that we are going to use. If we go with WebRTC, then a signaling server would be required, which can be based on the WebSocket protocol (for real-time communication purposes). 
2. If we use the asterisk, It uses SIP (session initiation protocol) for signaling. By signaling, I mean exchanging the public IPs of peers in the space so that communicate with each other by sending RTP streams.

What thoughts do you guys have about choosing technology for audio streaming over the internet?

**Comment by AntoTomAbraham** [comment]
#### Audio Streaming

Few ways to implement audio Streaming in the chat application

1. Using  3rd party paid tools like [Agora](https://www.agora.io/en/), [100ms](https://www.100ms.live/). if the aim is just to build an MVP then using 3rd party tools will be ideal since first 10,000 minutes every month is free.

2. WebRTC is the second option, we can use WebRTC+Firebase+Flutter to build the product (Serverless).

3. Custom backend is the next solution. Node JS, Express, MongoDB, WebRTC will be the best.

#### Joining Channel

1. Using 3rd party tools will make everything easy.

2. We will we use Signalling server (stun server) to connect devices

### Architecture

Provider or Bloc will be the best, since both are scalable and efficient. from my personal experience i will say its better to go with any of these two.

### Design Pattern and Audio Streaming

MVC pattern, This pattern is widely used and proven.

Flutter have many packages which will help to stream audio. 

### My Opinion

My  opinion will be to use Flutter in the frontend and NodeJS + Express + MongoDB + WebRTC in the backend as it is more scalable and good for long term. Using 3rd party tool will be nice if we want to build a MVP. Using  Firebase + Flutter + WebRTC will be nice but the problem with this will be less scalability

**Comment by ALIRAZA17** [comment]
@jddeep 
In terms of audio streaming, you can use a third-party library like Agora.io or Twilio Programmable Voice. These libraries provide APIs that allow you to add real-time audio and voice chat to your app. You will need to integrate this library into your Flutter project and configure it to work with Firebase.

To allow people to join a space, you can create a list of available rooms or spaces, and users can select a room to join. Once they join a room, they will be able to participate in the conversation by speaking or listening. You will need to implement a system to keep track of which users are in which room and ensure that users can only join one room at a time.

**Comment by Joymakwana2003** [comment]
Hello @jddeep sir,
To build an audio streaming platform like Clubhouse or Twitter Spaces, the following steps can be taken:

Platform Infrastructure: The first step would be to set up the platform infrastructure that can handle audio streaming. This can be done by using cloud-based services such as AWS, Google Cloud, or Microsoft Azure. These services offer scalable and reliable infrastructure to handle real-time audio streaming. If we don't want to use the paid services, then we can use open-source software like:
Apache Kafka: It is an open-source distributed event streaming platform that can handle messaging between different application components. Kafka is highly scalable and fault-tolerant, making it suitable for real-time audio streaming.
OpenStack: It is an open-source cloud computing platform that allows to set up a private cloud infrastructure. It provides virtual machines, storage, and networking services that can be used to build and deploy our application.

Audio Streaming Protocol: To handle audio streaming, we can use protocols like WebRTC (Web Real-Time Communication) which enables real-time communication between browsers and mobile applications. It supports high-quality audio streaming and works well on various devices and platforms.

Joining a Space: To join a space, users need to register and create a profile on the platform. Once they are logged in, they can browse the list of active spaces and join the one they are interested in. They can also create their own space and invite others to join.

Moderation: It is important to have moderators who can manage the space and ensure that the conversations are appropriate and respectful. Moderators can remove users who violate the platform's community guidelines or mute them if necessary.

Social Features: To make the platform engaging, we can include social features such as following, liking, commenting, and direct messaging. This will allow users to connect with each other and build a community around shared interests.

In terms of audio streaming, the platform can handle it by using the following approach:
Real-time Audio Encoding: The audio is captured from the user's device and encoded in real-time using a high-quality codec. This reduces latency and ensures that the audio quality is maintained.
Audio Delivery: The encoded audio is delivered to the platform's servers in real-time using a low-latency protocol such as WebRTC.
Audio Mixing: The audio from multiple users is mixed together in real-time, allowing everyone in the space to hear each other. The audio mixing can be done using software like AudioMixer or FFmpeg.
Audio Decoding: The mixed audio is then decoded and sent to each user's device using WebRTC, ensuring low-latency and high-quality audio.
Overall, building a platform like Clubhouse or Twitter Spaces requires careful consideration of the audio streaming protocol, moderation, and social features. Also, I have yet to use all the open-source software listed above, but I've used some of them. The rest of the software I got to know is from Google. So, I don't know whether it would be the best fit.

**Comment by tanishagupta1** [comment]
Hello @jddeep sir,

In order to make an audio streaming platform like Twitter spaces and clubhouse we need to consider below steps and pointers

**Front-end architecture**: we can use Flutter to build the mobile app's front end. It offers good support for real-time communication through WebRTC.

**Back-end architecture**: Use Firebase to handle user authentication and real-time data synchronization. Firebase offers tools that make it easy to build real-time applications, including Firebase Realtime Database and Cloud Firestore.

**Real-time communication**: Use WebRTC for real-time audio communication between participants. WebRTC is a browser-based communication protocol that offers low latency and high-quality audio transmission. We can use a third-party library like Twilio to handle WebRTC signaling and communication.

**Audio processing**: Use NodeJS to handle audio processing on the server side. It offers a wide range of libraries and tools for audio processing, such as the Web Audio API and the AudioContext API. You can also use AWS Lambda to handle serverless audio processing.

**Data storage**: We can use GCP or AWS to host a scalable NoSQL database, such as Google Cloud Datastore or Amazon DynamoDB. These databases can handle large volumes of data and offer good performance and scalability.

**Security**: We can use Firebase for user authentication and authorization, and implement encryption of audio traffic to prevent eavesdropping. We can also use AWS or GCP to host the app's back end on a secure and scalable infrastructure.

**Analytics**: Use Firebase Analytics to track user behavior and app usage, and integrate with Google Analytics or Mixpanel for more advanced analytics and reporting.

**Comment by Hbkharsh** [comment]
can we have a meet

**Comment by Hbkharsh** [comment]
Audio streaming: Flutter provides a package called audio players that can be used to play and control audio files. It supports various audio formats such as MP3, WAV, and FLAC. To handle real-time audio streaming.

backend : we can use nodejs and firebase for login authentication

for frontend we can use flutter
